basePath: /api
host: localhost:8080
info:
  contact: {}
  description: API for user authentication and management
  title: Authentication Service API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
